### ISSUE TITLE
Coworking proposal

### ISSUE THREAD

**Issue by zicmama** [blockexchange/blockexchange#10]
Hello,

My association is working on a decentralized datacenter based on ScutlleButt, IPFS and G1 Libre Money... Only Libre Softwares!!

To prepare promotion to the system, we are willing to open a "Metaverse" interface.
We choose minetest, and found blockexchange that is close to what will need to do...

Quickly, every player will be in charge of it's own "datacenter" and "digital consumption".
To remember confinment time, each build a 100 cube size world (local) where he makes his ideal "natural living place".

Every 10 minutes, worlds replicates through IPFS (cyphered by a shared key), then any one in the swarm can arrange every "litlle worlds" into a bigger one. Using friendship relation a a graph for distance between them...

I would be really grateful if you could indicate in your code where this patch could be done...

Send email to support@qo-op.com if you wish to participate.

**Comment by BuckarooBanzay** [comment]
> To prepare promotion to the system, we are willing to open a "Metaverse" interface.
We choose minetest, and found blockexchange that is close to what will need to do...

Thank you for the interest in this project, it is still in a work-in-progress / pre-alpha stage at this moment...

> Quickly, every player will be in charge of it's own "datacenter" and "digital consumption".
To remember confinment time, each build a 100 cube size world (local) where he makes his ideal "natural living place".

Sounds interesting, do you have some white-papers or a solid concept already available on how you plan to do this? Maybe a reference-project for the technology?

> I would be really grateful if you could indicate in your code where this patch could be done...

Yeah, uhm, i don't think there would be *one* place in the code to modify for that. This (if i understand correctly) would have been done on several places, some workflows may have to be changed for this to work...

> Send email to support@qo-op.com if you wish to participate.

Sure thing, let me just get this to a stable state first and fill me in on the technological details if possible...

**Also**: do you have monetization plans for this or will this be a "free" service?

**Comment by zicmama** [comment]
Great you like te idea... To give you a better picture.
This project is inspired by https://madeinzion.org
The Metaverse game based on minetest is for sustainable living promotion and experiments sharing in different climates. As a framework for a new society model.

After a deeper look at your code, as the file size is small, it could be more convenient to use ScuttleButt messaging protocol to share "little worlds" between friends ;)
More detail about it https://ssbc.github.io/scuttlebutt-protocol-guide/
Does a common language API exists? 

As member of https://axiom-team.fr association, we are promoting June (G1), a stable mesurement unit called "Monnaie Libre" and inform the public about its existence.
So "monetization" is better than ever included !

More detail about it https://duniter.org + https://cesium.app
Wallets can be used in ScuttleButt https://viewer.scuttlebot.io/%252yULOGPGU68VKGvBJhNYxBz5yQ6NIfmeBovFP6WubDw%3D.sha256

**Comment by BuckarooBanzay** [comment]
the server-part is now rewritten in `golang` and some of the points above may not be accurate anymore, if there is still interest feel free to reopen/post another issue
