### ISSUE TITLE
Compression

### ISSUE THREAD

**Issue by ExeVirus** [blockexchange/blockexchange#46]
Minetest schematics tend to be bloated in terms of bytes and data, to save on bandwidth, have you considered integrating .zip compression? minetest has this built-in, though I don't think it's exposed to the lua api yet. 

That said, there's also work ongoing to put better compression via zstd in, so be on the lookout for that. Great work! Just wanted to share something that might help:)

**Comment by BuckarooBanzay** [comment]
Thanks for the kind words :+1: 

Compression is currently only applied on the database level (https://github.com/blockexchange/blockexchange_server/blob/9f0af3fdb49d89a01a11f2585406c5faaf7fe136/src/util/serializer.js#L64-L67).
There is no compression for the in-flight map-data yet, it is transferred as plain json-data (it may be compressed with gzip if the client can handle that, haven't tested that yet)

In the future, if there is significant benefit in another compression-strategy, it could be added with different version-headers, i don't see a problem with retrofitting that later :smirk:

**Comment by BuckarooBanzay** [comment]
closing this, i rewrote the server-part from nodejs to go and also changed the serialization-format and compression:

The data and metadata is now compressed with `deflate` (both the server and the mod can use this) so the most cpu-intensive operation can be done on the client/mod side, the server now only needs this for the preview, all other things are basically just pass-through.
In-flight requests encode the binary data now with `base64`
Docs: https://github.com/blockexchange/blockexchange_server#serialized-mapblock-format

About the size-issues: i don't have worries about that yet, also: air-only blocks are handled now properly :)

Feel free to comment/reopen if you have ideas or issues :+1:
