### ISSUE TITLE
Store block area info in node meta

### ISSUE THREAD

**Issue by Emojigit** [blockexchange/blockexchange#51]
As far as I know, the HUD element cannot remove. I suggest storing area info in metadata to avoid marking non-imported or exported blocks as Blockexcharge blocks.

**Comment by BuckarooBanzay** [comment]
> I suggest storing area info in metadata

Tried that, doesn't work if you have larger schematics with the metadata laying around _somewhere_ :confounded: 
I'm not a fan of off-world storage but that is sadly the only viable option.

> As far as I know, the HUD element cannot remove.

I think an option for that and maybe for area-tracking would be in order :+1:

**Comment by BuckarooBanzay** [comment]
Area-info is now stored in the `blockexchange:controller` block, all area-hud hacks have been removed, closing this
