### ISSUE TITLE
Upload Enable mod to ，generate an integrated compression package

### ISSUE THREAD

**Issue by Pantyhose-X** [blockexchange/blockexchange#52]
I can't find the related mod 
`Content.minetest` `Forum.Minetest` also has no correlation MOD
![113](https://user-images.githubusercontent.com/42504385/119248107-10472380-bbe3-11eb-8978-9bf8dc5d97e3.JPG)
No correlation MOD only prints unknown block
![112](https://user-images.githubusercontent.com/42504385/119247877-6915bc80-bbe1-11eb-903b-2d883d4e9783.JPG)

`/bx_load_unzip_integrated` [username] [schemaname] [integrated mod name]

**Comment by BuckarooBanzay** [comment]
You are searching for the mods, right?

In that case, i think adding a link to the schematic page (the page on the top screenshot) with the following link pattern should do the trick: `https://content.minetest.net/metapackages/<modname>`

This would result in something like that and is quite accurate (except for the 2 unrelated games for the `scifi_nodes` result):
* `prefab` https://content.minetest.net/metapackages/prefab/
* `factory_bridges` https://content.minetest.net/metapackages/factory_bridges/
* `scifi_nodes` https://content.minetest.net/metapackages/scifi_nodes/
* `default` https://content.minetest.net/metapackages/default/
* `air` already built-in

Would those links on the modname-badges (the green things with the modname) help for your search? :thinking: 

Not sure if a "zip" download of the mods would be feasible, the search-results from the contentdb are something ambigous

**Comment by Pantyhose-X** [comment]
> You are searching for the mods, right?
> 
> In that case, i think adding a link to the schematic page (the page on the top screenshot) with the following link pattern should do the trick: `https://content.minetest.net/metapackages/<modname>`
> 
> This would result in something like that and is quite accurate (except for the 2 unrelated games for the `scifi_nodes` result):
> 
> * `prefab` https://content.minetest.net/metapackages/prefab/
> * `factory_bridges` https://content.minetest.net/metapackages/factory_bridges/
> * `scifi_nodes` https://content.minetest.net/metapackages/scifi_nodes/
> * `default` https://content.minetest.net/metapackages/default/
> * `air` already built-in
> 
> Would those links on the modname-badges (the green things with the modname) help for your search? 🤔
> 
> Not sure if a "zip" download of the mods would be feasible, the search-results from the contentdb are something ambigous

![113](https://user-images.githubusercontent.com/42504385/119364961-92c70480-bd03-11eb-9bca-b99dcb27a7dc.JPG)

* `https://blockexchange.minetest.land/` Download all
* Yes Do not redirect to `https://content.minetest.net/metapackages/<modname>`
