### ISSUE TITLE
worlds map.sqlite exchange

### ISSUE THREAD

**Issue by Pantyhose-X** [blockexchange/blockexchange#53]
Minetest>New>mapgen>singlenode
Enter the world
`/bx_world` [username] [schemaname]

**Comment by BuckarooBanzay** [comment]
Do you mean as an export or an import?
Do i get this right: You want to import an existing schematic into an empty world? What about the mods?

**Comment by Pantyhose-X** [comment]
> Do you mean as an export or an import?
> Do i get this right: You want to import an existing schematic into an empty world? What about the mods?

Import
yes import an existing schematic into an empty world

**Comment by BuckarooBanzay** [comment]
>  yes import an existing schematic into an empty world

Err, thats exactly what this mod and the application tries to solve:
To "import" this schematic: https://blockexchange.minetest.land/#/schema/BuckarooBanzai/borg_cube
You can use those commands to load it (see bottom of the page also):
```
/bx_pos1
/bx_load BuckarooBanzai borg_cube
```

**Comment by Pantyhose-X** [comment]
Import
import an existing map.sqlite into an empty world
